export const PARKING_SESSION_REPOSITORY = Symbol('PARKING_SESSION_REPOSITORY');

export const CLIENT_REPOSITORY = Symbol('CLIENT_REPOSITORY');

export const VEHICLE_TYPE_REPOSITORY = Symbol('VEHICLE_TYPE_REPOSITORY');

export const TARIFF_REPOSITORY = Symbol('TARIFF_REPOSITORY');

export const EMAIL_NOTIFICATION_GATEWAY = Symbol('EMAIL_NOTIFICATION_GATEWAY');

export const REGISTER_ENTRY = Symbol('REGISTER_ENTRY');

export const REGISTER_EXIT = Symbol('REGISTER_EXIT');

export const GET_SESSION = Symbol('GET_SESSION');

export const LIST_VEHICLE_TYPES = Symbol('LIST_VEHICLE_TYPES');

export const LIST_ACTIVE_SESSIONS_PAGINATED = Symbol('LIST_ACTIVE_SESSIONS_PAGINATED');

export const LIST_SESSIONS_PAGINATED = Symbol('LIST_SESSIONS_PAGINATED');

export const GET_TARIFF = Symbol('GET_TARIFF');

export const UPDATE_TARIFF = Symbol('UPDATE_TARIFF');

